### ISSUE TITLE
Syntax settings are not applied when file is opened with "Goto Anything"

### ISSUE THREAD

**Issue by alvion427** [reywood/sublime-project-specific-syntax#1]
When using the Goto Anything command to open a file settings are not correctly applied because view.window() is None in _get_project_specific_syntax().  Suggest using sublime.active_window() instead.

**Comment by reywood** [comment]
Thanks for the bug report and apologies for my general slowness in fixing it. A new version is up.

**Comment by alvion427** [comment]
Thanks for fixiing it!
