### ISSUE TITLE
Syntax file not found if ...

### ISSUE THREAD

**Issue by br4nnigan** [reywood/sublime-project-specific-syntax#14]
...if I don't place the .tmLanguage file directly into "packages" as the error message says. But that's not how the file structure is. I have the .sublime-package in "Installed Packaged", or the language file in "packages/PackageName/PackageName.tmLanguage". It's not recognized. Windows 7. Tested with JSX package.

**Comment by reywood** [comment]
Try using the `Copy syntax setting to clipboard` menu option via right-click or command palette as mentioned in the README.
