### ISSUE TITLE
Feature request for 'Copy syntax setting to clipboard'

### ISSUE THREAD

**Issue by jamiewilson** [reywood/sublime-project-specific-syntax#16]
Hey, first off, thanks for this project. 

I was wondering if there is any reason why the copy to clipboard feature doesn't copy the whole settings object that you need for it to work. For example, rather than getting just:

```
"\\.html$": ["Handlebars", "grammars", "Handlebars"]
```

wouldn't it be awesome if you got:

```
"syntax_override": {
        "\\.html$": ["Handlebars", "grammars", "Handlebars"]
}
```

Just a thought. Thanks!

**Comment by reywood** [comment]
Good idea! I've gone ahead and done you one better. I just released a new version that will include the `"syntax_override"` bit if there isn't already one in your project settings file. If there are already syntax override settings, then it'll just give you the single line, as before.

**Comment by jamiewilson** [comment]
Very cool. thanks!
