### ISSUE TITLE
How to open ALL files with selected syntax

### ISSUE THREAD

**Issue by andrewcole50** [reywood/sublime-project-specific-syntax#17]
In my project, I want to open ALL files with a certain syntax. I can't seem to get it to work. Most files don't have file extensions. Here's what I've tried according to my regex knowledge:

```
{
	"folders":
	[
		{
			"path": "J:\\"
		}
	],
	"syntax_override": {
		"*": ["MultiValue BASIC", "jbase", "jbase-basic"]
	}
}
```

**Comment by reywood** [comment]
Try using a `.` instead of a `*`

**Comment by andrewcole50** [comment]
Works perfectly!!! Thank you!!
