### ISSUE TITLE
Add support for .sublime-syntax files

### ISSUE THREAD

**Issue by queengooborg** [reywood/sublime-project-specific-syntax#18]
I recently defined my own custom combination of HTML and Python for web2py views, and I want my project to automatically assume that all HTML files within are web2py view files, which is how I found this project.  However, my syntax definition is written in Sublime Text's new `.sublime-syntax` definitions, rather than a TextMate language (and I have no intention of using this legacy format).  Unfortunately, it seems that this project only wants to load TextMate language files, and I would like to request support for Sublime Syntax files.

**Comment by reywood** [comment]
I don't use Sublime anymore, so it could be a while before I take a look at this. Perhaps someone can submit a PR for this.

**Comment by reywood** [comment]
New release pushed which should fix this. Thanks to @n2taylor for the PR!
