### ISSUE TITLE
Issues with finding syntax files in Windows

### ISSUE THREAD

**Issue by ErichDonGubler** [reywood/sublime-project-specific-syntax#2]
Hey there! Love this plugin, and it's working great on Arch Linux. After installing on Windows 8.1, though, I have an issue where I cannot get what I'm sure is a valid syntax spec path to be found. Here is my current `*.sublime-project` file (which I use at my Jekyll [blog](http://erichdongubler.github.io/)):

``` json
{
    "folders":
    [
        {
            "follow_symlinks": true,
            "path": ".."
        }
    ],
    "build_systems":
    [
        {
            "name": "Run Jekyll",
            "working_dir": "$project_path/..",
            "shell_cmd": "gnome-terminal -e 'bash --login -c \"jekyll serve\"'",
            "windows":
            {
                "shell_cmd": "start jekyll serve"
            }
        }
    ],
    "syntax_override":
    {
        "\\.html$": [ "Jekyll", "Syntaxes", "HTML (Jekyll)" ]
        ,"\\.md$": [ "Jekyll", "Syntaxes", "Markdown (Jekyll)" ]
    },
    "settings":
    {
      "Jekyll":
      {
          "posts_path": "../_posts",
          "drafts_path": "../_drafts",
      }
    }
}
```

This same configuration worked correctly on Arch, so I'm not sure what's gone wrong. I HAVE noticed that there is no `Cache` folder in my `%appdata%` folder. Could this be the source of the problem?

Thanks in advance!

**Comment by reywood** [comment]
I haven't tested this plugin on Windows and don't currently have access to a Windows box, so I'm afraid I can't be much help here. I'll leave this open for now in hopes that someone else might happen along who can offer up some insight.

**Comment by reywood** [comment]
Could you try opening the python console in Sublime Text (`ctrl+`` or `View > Show Console`) and running `view.settings().get('syntax')` with one of your HTML files open? I'm curious if the output has forward slashes or back slashes.

**Comment by reywood** [comment]
I was able to spin up a Windows VM and try this out. Looks like Sublime always uses forward slashes for syntax file paths regardless of OS. Version 0.0.5 of this package should fix your problem.

**Comment by ErichDonGubler** [comment]
Hey, sorry for disappearing! Confirmed that the fix is working for me. Thanks for the prompt reply! :)
