### ISSUE TITLE
Mac syntax file not found

### ISSUE THREAD

**Issue by mpcabd** [reywood/sublime-project-specific-syntax#3]
I have Sublime Text 3, and I wasn't able to easily direct the plugin to the syntax file. I was working on Mason files, and I have installed the Mason package, and I couldn't find the Mason.tmLanguage file, my folder structure looks like:

```
. ~/Library/Application Support/Sublime Text 3/
+-- Packages
+-- Cache
|   +-- Mason
|       +-- Syntaxes
|           +-- Mason.tmLanguage.cache
+-- Installed Packages
    +-- Mason.sublime-package (zipped file)
        +-- Mason
            +-- Syntaxes
                +-- Mason.tmLanguage
```

And to solve it I called `view.settings().get('syntax')` on the console and got `'Packages/Mason/Syntaxes/Mason.tmLanguage'` back, so I knew I had to set the path to:

```
....
"\\.html$": [ "Mason", "Syntaxes", "Mason" ],
....
```

I have Sublime Text 3 build 3065 on Mac OS X 10.10.2.

So I think that the documentation should change and include that the path can be inside the zipped `.sublime-package` file, or easier to get it by setting the syntax manually and then calling `view.settings().get('syntax')` on the console.

Regards.

**Comment by radarseven** [comment]
@mpcabd Thanks for this info, it was super helpful!

**Comment by reywood** [comment]
Yeah, it's a pain to find the right magic words to specify a syntax file right now. Perhaps I'll add a command that can be accessed from the command palette to get the current syntax path. Thanks for the idea!

**Comment by reywood** [comment]
New version is out. Relevant updates from the README:

> The easiest way to construct these key/value pairs is to open an existing file in your project, set the syntax you would like to use for that file with the `View > Syntax > ...` menus (or the command palette), right click in the file editor area, and select the `Project Specific Syntax > Copy syntax setting to clipboard` menu item. This menu item is also available via the command palette. Once copied to the clipboard, simply open your project file and paste the new key/value pair into the `syntax_override` section. Be sure to add any necessary commas to separate multiple key/value pairs so your project file is still valid JSON.

**Comment by radarseven** [comment]
@reywood Great update! Thanks for this helpful tool, Sean.

**Comment by mpcabd** [comment]
Nice idea, but (1) the button seems to stay inactive or disabled for me, even after changing the syntax a couple of times, see this image

![image](https://cloud.githubusercontent.com/assets/644992/6268767/76c273ec-b84f-11e4-8fa3-16802518dfde.png)

(2) I don't think that this action needs to stay permanently in the context menu, it won't be used as frequently as the other commands there.

Cheers.

**Comment by reywood** [comment]
Try restarting Sublime Text. Happened to me too. Seems like a bug in ST.

**Comment by mpcabd** [comment]
Right, it worked after a restart, but IMHO it's not needed in the context menu, just in the command palette (which BTW also needed a restart to show the command).
