### ISSUE TITLE
Broke my comments!

### ISSUE THREAD

**Issue by litchfield** [reywood/sublime-project-specific-syntax#5]
My comment toggle options (along with various others) were greyed out after installing this. Worked again after uninstalling.

:-(

**Comment by litchfield** [comment]
This one worked though?
http://braindump.io/sublime-text/2014/09/26/project-specific-syntax-highlighting-in-sublime-text-3.html

**Comment by reywood** [comment]
I'm not sure what you mean by "comment toggle options". Could you clarify? A screenshot might be helpful.
