### ISSUE TITLE
I can't get this working for some reason? 

### ISSUE THREAD

**Issue by vladyn** [reywood/sublime-project-specific-syntax#7]
I have 
    "syntax_override": {
                "\.html$": ["AngularJS", "AngularJS"]
            },
in my project and when opening files with .html they have HTML syntax applied instead of HTML Angular

Any ideas?

**Comment by reywood** [comment]
You should have two backslashes before the `.html`, like so:

``` javascript
{
    "syntax_override": {
        "\\.html$": ["AngularJS", "AngularJS"]
    }
}
```

If that doesn't fix it, try opening the console (`View -> Show Console` or `Ctrl+`` ) and then opening an HTML file. You may see an error.

**Comment by vladyn** [comment]
hm - good point - I do have. And this is under windows. I haven't try it on my mac
