### ISSUE TITLE
Specific Syntax > Copy syntax setting to clipboard not working

### ISSUE THREAD

**Issue by ddeath** [reywood/sublime-project-specific-syntax#8]
Hi there,
it seems that Specific Syntax > Copy syntax setting to clipboard is broken in build 3103 in Sublime Text 3.

Error in console:
Syntax does not match expected format: Packages/JavaScript/JSON.sublime-syntax

I guess it is because of file extension?

**Comment by reywood** [comment]
Thanks for reporting. Just pushed up a new release to fix this. Should be available soon.
