### ISSUE TITLE
Syntax not changed correctly

### ISSUE THREAD

**Issue by kanedo** [reywood/sublime-project-specific-syntax#9]
Hi,
I created my own syntax in `Packages/User/LaTeX with Headline.tmLanguage` so my project settings look like this:

``` json
"syntax_override":
    {
        "\\.tex$":
        [
            "User",
            "LaTeX with Headline"
        ]
    }
```

when I open a `.tex` file inside the project the console shows `Switched syntax to: User/LaTeX with Headline` but the syntax still remains the default `LaTeX`.

Any idea what went wrong?

**Comment by reywood** [comment]
Could you try opening a tex file and manually setting the syntax to your custom syntax. Then, use the "Copy syntax setting to clipboard" to see what it thinks is the correct setting.

![Copy syntax screenshot](http://i.imgur.com/elwFsw1.png)

**Comment by kanedo** [comment]
I did this and it copied the exact same thing (that’s how I got it in the first place)

**Comment by reywood** [comment]
Can you create a gist with the contents of your syntax file?

**Comment by kanedo** [comment]
of course:
https://gist.github.com/kanedo/872a294b0786c5576495

**Comment by reywood** [comment]
Sorry for the delay getting back to you. I tried out your syntax file and didn't have any problems. Not sure why you're having issues.

**Comment by ilyakam** [comment]
@kanedo: I just had a similar problem. The caveat was that I didn't put `"syntax_override"` in the right place in the `*.sublime-project` file. The `README` file doesn't make it 100% clear. 

What you want to do, is you want to put `"syntax_override"` **at the root the of the object**. Chances are you already have `"folders"` in that file. This should a sibling to that key. Like so:

``` json
// some.sublime-project

{
  "folders": [ ... ],

  "syntax_override": {
    "\\.tex$": ["User", "LaTeX with Headline"]
  }
}
```

**Comment by reywood** [comment]
Closing since I can't recreate, but feel free to let me know if there are any updates on this problem.
